// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0zK_GRqC1ORz1UOXlyykEluh5mjTiDaw',
    appId: '1:147662724869:web:7a6fbe89bcaef361cba16c',
    messagingSenderId: '147662724869',
    projectId: 'sobaapp-79efd',
    authDomain: 'sobaapp-79efd.firebaseapp.com',
    storageBucket: 'sobaapp-79efd.firebasestorage.app',
    measurementId: 'G-PWB5PQ15N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXoyPtoPnpyIsajxd-gn3V8o9ubwAa3iQ',
    appId: '1:147662724869:android:049931dbc33f8c3dcba16c',
    messagingSenderId: '147662724869',
    projectId: 'sobaapp-79efd',
    storageBucket: 'sobaapp-79efd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfnJP5_W8vXWkcHa5DZfV1JcWSyiJPI5k',
    appId: '1:147662724869:ios:8e5bed83886fce92cba16c',
    messagingSenderId: '147662724869',
    projectId: 'sobaapp-79efd',
    storageBucket: 'sobaapp-79efd.firebasestorage.app',
    iosBundleId: 'com.example.sobaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfnJP5_W8vXWkcHa5DZfV1JcWSyiJPI5k',
    appId: '1:147662724869:ios:8e5bed83886fce92cba16c',
    messagingSenderId: '147662724869',
    projectId: 'sobaapp-79efd',
    storageBucket: 'sobaapp-79efd.firebasestorage.app',
    iosBundleId: 'com.example.sobaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0zK_GRqC1ORz1UOXlyykEluh5mjTiDaw',
    appId: '1:147662724869:web:7a1b987ab0c5613fcba16c',
    messagingSenderId: '147662724869',
    projectId: 'sobaapp-79efd',
    authDomain: 'sobaapp-79efd.firebaseapp.com',
    storageBucket: 'sobaapp-79efd.firebasestorage.app',
    measurementId: 'G-5ZTQZH7RC0',
  );
}
